/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jI0eEebzpqy
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function SignIn() {
    return (
        <Card>
            <CardHeader className="sm:mx-auto sm:w-full sm:max-w-sm flex justify-center">
                <CardTitle className="text-2xl">로그인</CardTitle>
                <CardDescription>서비스 이용을 위해 아이디와 비밀번호를 입력해주세요.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 mx-auto w-full max-w-sm">
                <div className="space-y-2">
                    <Label htmlFor="loginID">아이디</Label>
                    <Input id="loginId" placeholder="Enter your login ID" required type="text" />
                </div>
                <div className="space-y-2">
                    <Label htmlFor="password">비밀번호</Label>
                    <Input id="password" required type="password" />
                </div>
            </CardContent>
            <CardFooter>
                <Button className="w-full text-white bg-neutral-900">로그인</Button>
            </CardFooter>
            <div className="mt-4 mb-7 text-center text-sm">
                회원이 아니십니까?
                <Link className="underline mx-1 text-blue-500" href="/signup">
                    회원가입 하러가기
                </Link>
            </div>
        </Card>
    );
}
